### ISSUE TITLE
what is a config.perl.txt?

### ISSUE THREAD

**Issue by LeeYEAH2** [ChenGuangji/BirdsSoloLTRs#1]
Hi, I found that in your ltrpairwise.pl 
you have code below:
my %config;
parse_config("$Bin/config.perl.txt",\%config);
I understand that the $bin is where the .pl locates， but i didn't find file like config.perl.txt as also not provided by you.
is there any mistaken in this?

**Comment by ChenGuangji** [comment]
> Hi, I found that in your ltrpairwise.pl you have code below: my %config; parse_config("$Bin/config.perl.txt",%config); I understand that the $bin is where the .pl locates， but i didn't find file like config.perl.txt as also not provided by you. is there any mistaken in this?

The file has been uploaded as script/config.perl.txt which contains the address of the mafft software.

`mafft = "PATH of mafft-ginsi"`

**Comment by LeeYEAH2** [comment]
I see， that makesense now. thx a lot
